### ISSUE TITLE
[QS FPS Info] Tile toggling not working

### ISSUE THREAD

**Issue by dreamwhite** [crdroidandroid/android_device_oneplus_sdm845-common#3]
# Basic device infos

**Device:** OnePlus 6T (fajita)
**Vendor**: OxygenOS 10.3.8
**crDroid version**: 7.3 build February 23, 2021

# Short description of the problem

Despite this  is a low-priority issue, and can be ignored, I just experienced the following bug.
Toggling `FPS Info` tile doesn't work. The only workaround is enabling `Show refresh rate` option in `Developer Options/Debug` settings. 

# Steps to reproduce the bug

1. enable Android developer options (spam tap on `About Phone/Build Number`)
2. Open notification panel and swipe down to expand it
3. Click on the `pencil-shaped icon` and drag `FPS Info` into the tiles list
4. Click on `FPS Info` tile

Please let me know how to provide the logs, despite I already tried getting them through `Matlog` without success. The only thing I can see is `started/stopping CurFPSThread`

# Screenshots 

- FPS Info tile

![FPS Info tile](https://user-images.githubusercontent.com/17933708/109213133-8a1c6c00-77b0-11eb-84ea-ddb45e0312d6.png)

- Matlog output

![Matlog output](https://user-images.githubusercontent.com/17933708/109212561-f77bcd00-77af-11eb-9940-ccf4ec72d3d5.png)

- Developer Options setting (Picasso goes brrrrrr)

![image](https://user-images.githubusercontent.com/17933708/109213780-4d9d4000-77b1-11eb-9ea6-27b8490c8cce.png)

# PS

Please let me know if you need more logs, if those already provided are not enough

**Comment by neobuddy89** [comment]
check for sepolicy denials.

**Comment by dreamwhite** [comment]
> check for sepolicy denials.

😅 How should I check them?
I have SELinux status on Enforcing. Is this what are you talking about?

**Comment by gwolf2u** [comment]
Please provide logcat

@MaWalla 
This known issue?

**Comment by dreamwhite** [comment]
> Please provide logcat

@gwolf2u May I ask you if the following logcat contains the required data?

[logcat.txt.zip](https://github.com/crdroidandroid/android_device_oneplus_sdm845-common/files/6048797/logcat.txt.zip)

I obtained it via `adb logcat > logcat.txt` and toggled on/off repeatedly `FPS Info` QS tile.

**Comment by MaWalla** [comment]
> Please provide logcat
> 
> @MaWalla
> This known issue?

Known since this issue was created, I can reproduce it on my phone though.
